Use nicer Debug implementations
time-rs/time pull request #509
Opened 2022-09-24 18:20 UTC by xy2iii

Same as Display for now

Closes #503.

2022-10-01 06:06 UTC, jhpratt requested changes
Alright, let's do this. Only change is deduplication, as the PR as-is needlessly doubles up the code.

You'll also need to rebase, though this shouldn't cause any conflicts. This is because I updated CI, so it won't pass on the PR unless it's rebased.

2022-10-01 06:06 UTC, jhpratt commented on src/date.rs
> +        }
Let's reuse the existing `Display` implementation. No need to duplicate code, after all.

```suggestion
        fmt::Display::fmt(self, f)
```

2022-10-01 08:01 UTC, jhpratt requested changes

2022-10-01 09:20 UTC, xy2iii commented on src/time.rs
> +}
Ah my bad, should be in the right location now

2022-10-02 02:44 UTC, jhpratt commented
It appears as though nothing has been changed since my previous comment. Did you forget to push something?

2022-10-02 08:29 UTC, xy2iii commented
My bad :) Should be good now.

2022-10-02 09:30 UTC, jhpratt commented
Looks good now! I'll take a final look over once I'm on my laptop. I also want to look into the internal compiler error when generating coverage, as that should never happen (not your fault).

2022-10-03 05:05 UTC, jhpratt commented
Unfortunately I am able to reproduce the internal compiler error on the currently nightly. This is unrelated to this PR, as I can reproduce it on the current main. Consequently I see no reason not to merge this.

Thank you!

2022-10-03 05:05 UTC, merged