Fix new Rust 1.67 clippy errors
time-rs/time pull request #545
Opened 2023-01-29 02:22 UTC by Kinrany

Fixes new Clippy warnings that came with Rust 1.67.

Warnings:

 * [uninlined_format_args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args)
 * [unchecked_duration_subtraction](https://rust-lang.github.io/rust-clippy/master/index.html#unchecked_duration_subtraction)

Also fixes a couple of formatting issues:
 * comments around [undocumented_unsafe_blocks](https://rust-lang.github.io/rust-clippy/master/index.html#undocumented_unsafe_blocks): `//false positive` was being considered part of the same comment block with the following `// SAFETY: ...` comment, so the latter was indented to be on the same level. Like
   ```rust
   let x = 0; // first value
              // will be used later
   ```
 * if-else split into multiple lines

2023-02-16 06:05 UTC, jhpratt requested changes
This does more than just fix clippy errors. But regardless, some changes are requested. There is also a warning in the tests that was not addressed. I'm not sure what formatting issue you're referring to — formatting is checked in CI on every push.

2023-02-16 06:05 UTC, jhpratt commented on time/src/instant.rs
> +/// # Panics
This documentation should be on the method, not the trait.

2023-02-16 06:05 UTC, jhpratt commented on time/src/date_time.rs
> +    };
I don't care for this change. The existing code is acceptable, and it's just a bug with clippy.

2023-02-19 04:45 UTC, jhpratt commented
I am making the changes myself so that I can move ahead with other work without CI failing. Closing for that reason.

2023-02-19 04:45 UTC, closed without merging

2023-02-19 05:28 UTC, Kinrany commented
Absolutely, sorry I didn't have time! I'm glad if the PR was of any help.

2023-02-19 05:29 UTC, jhpratt commented
Not an issue! I ended up pushing changes similar to what would have been the end result of this PR.